name: Crawler Demo Action
run-name: Crawler Demo Action

# 觸發此 action 的時機
on:
  schedule:
    - cron: "55 12 * * *"  # UTC 每天下午 12:55 執行此 action（等同於台灣晚上 8:55 執行）
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  crawler-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install Python Dependency
        run: pip3 install requests
      - name: Run crawler.py  # 前面都是在安裝 Python 環境，這裡才是真的去執行 crawler.py 的程式
        run: python crawler.py
      - name: Commit Data Back To GitHub Repo  # 將爬到的數據 commit 回 GitHub repo
        run: |
          git config --global user.name "crawler-bot"
          git config --global user.email "crawler-bot@gmail.com"
          git add . && git commit -m "daily crawl"
          git push origin main
